---
- name: Restart mc_menu service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    state: started
    name: "{{ item }}"
  loop: ["mc-menu.service", "mc-menu.path"]
  listen: handler_restart_mcmenu
